server:
  port: 8081
spring:
  cloud:
    stream:
      default-binder: kafka # 默認綁定器
      kafka: # 如果用的是 rabbitMQ 這裡填 rabbit
        binder:
          brokers: # Kafka 的訊息中間件服務位址
          - localhost:9092
          auto-add-partitions: true
        #          auto-create-topics: false
        bindings:
          my-in:
            consumer:
              auto-commit-offset: false
          reply-in:
            consumer:
              auto-commit-offset: false
          poll-in:
            consumer:
              auto-commit-offset: false
              max-poll-records: 10


      bindings:
        my-in: # 通道名稱
          binder: kafka
          destination: testTopic # 訊息發送的目的地，對應 topic
          content-type: application/json # 訊息格式
          group: testTopic-input-group # 對應 kafka 的 group
        my-out:
          binder: kafka
          destination: testTopic
          content-type: application/json
        reply-in:
          binder: kafka
          destination: reply
          content-type: application/json
          group: reply-input-group-1
        reply-out:
          binder: kafka
          destination: reply
          content-type: application/json
        poll-out:
          destination: polledConsumer
          content-type: application/json
        poll-in:
          destination: polledConsumer
          group: polledConsumer-input-group
          content-type: application/json

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
#      acks: all
#      retries: 3
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false