server:
  port: 8081
spring:
  cloud:
    stream:
      default-binder: kafka # 默認綁定器
      kafka: # 如果用的是 rabbitMQ 這裡填 rabbit
        binder:
          brokers: # Kafka 的訊息中間件服務位址
          - localhost:9092
#          auto-create-topics: false
          auto-add-partitions: true
      bindings:
        my-in: # 通道名稱
          binder: kafka
          destination: testTopic1 # 訊息發送的目的地，對應 topic
          content-type: application/json # 訊息格式
          group: output-group-2 # 對應 kafka 的 group
        my-out:
          binder: kafka
          destination: testTopic2
          content-type: application/json
          group: input-group-2
        reply-in:
          binder: kafka
          destination: reply
          content-type: application/json
          group: input-group-1
        reply-out:
          binder: kafka
          destination: reply
          content-type: application/json
          group: output-group-1
        poll-out:
          destination: polledConsumer
          content-type: application/json
        poll-in:
          destination: polledConsumer
          group: polledConsumerApplication
          content-type: application/json
  kafka:
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      value-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
