server:
  port: 8081

spring:
  cloud:
    stream:
      # 同一个应用的实例数量和实例索引
      instance-count: 2
      instance-index: 0
      default-binder: kafka # 默認綁定器
      default:
        consumer:
          headerMode: headers
          partitioned: true
          concurrency: 1
#        producer:
#          partitionKeyExpression: payload.id
#          partitionCount: 2
#          partitionKeyExtractorName: PartitionKeyExtractor
#          partitionSelectorName: PartitionSelector

      bindings:
        my-in: # 通道名稱
          binder: kafka
          destination: testTopic # 訊息發送的目的地，對應 topic
          content-type: application/json # 訊息格式
          group: testTopic-input-group # 對應 kafka 的 group
        my-out:
          binder: kafka
          destination: reply
          content-type: application/json
        poll-in:
          binder: kafka
          destination: polledConsumer
          content-type: application/json
          group: polledConsumer-input-group
        poll-out:
          binder: kafka
          destination: reply
          content-type: application/json

      kafka: # 如果用的是 rabbitMQ 這裡填 rabbit
        binder:
          brokers: # Kafka 的訊息中間件服務位址
          - localhost:9092
          auto-add-partitions: true
          auto-create-topics: true
          headers: key
        bindings:
          my-in:
            consumer:
              auto-commit-offset: false
              auto-rebalance-enabled: false
          poll-in:
            consumer:
              auto-commit-offset: false
              auto-rebalance-enabled: false

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false