spring:
  cloud:
    stream:
      bindings:
        input: # 通道名稱
          destination: testTopic # 訊息發送的目的地，對應 topic
          group: myGroup # 對應 kafka 的 group
          contentType: application/json # 訊息格式
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
            backOffMultiplier: 2.0
        output:
          destination: reply
          contentType: application/json
        error:
          destination: myErrors

      kafka: # 如果用的是 rabbitMQ 這裡填 rabbit
        binder:
          brokers: # Kafka 的訊息中間件服務位址
          - localhost:9092
          autoAddPartitions: false
          autoCreateTopics: true
        bindings:
          input:
            consumer:
              autoCommitOffset: true
              autoCommitOnError: false
              enableDlq: true
#              auto-rebalance-enabled: false
#              auto-bind-dlq: true
#              republish-to-dlq: true